//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by pvengine.rc
//
#define CM_FIRST                        2000
#define CM_ALERT                        2000
#define CM_AUTORENDER                   2005
#define CM_CLEARQUEUE                   2010
#define CM_COMMANDLINE                  2015
#define CM_TOOLBARCMDLINE               2017
#define CM_CONTINUECURRENT              2020
#define CM_DEMO                         2025
#define CM_BENCHMARK                    2027
#define CM_RENDERSHOW                   2030
#define CM_DUMPPANE                     2035
#define CM_FILEEXIT                     2040
#define CM_FILEQUEUE                    2045
#define CM_FILERENDER                   2050
#define CM_STOPRENDER                   2051
#define CM_FORCE8BITS                   2055
#define CM_HELPABOUT                    2060
#define CM_HELPCONTENTS                 2065
#define CM_HELPBUGS                     2070
#define CM_HELPPOVWIN                   2080
#define CM_HELPSCENE                    2085
#define CM_HELPLOOKUP                   2087
#define CM_PRESERVEMESSAGES             2090
#define CM_RENDERACTIVE                 2095
#define CM_RERUNCURRENT                 2105
#define CM_RERUNDIALOG                  2110
#define CM_RERUNLAST                    2115
#define CM_SOURCEFILE                   2130
#define CM_TILEDBACKGROUND              2140
#define CM_BACKGROUNDCOLOUR             2145
#define CM_BACKGROUNDBITMAP             2150
#define CM_TEXTCOLOUR                   2165
#define CM_FONT                         2175
#define CM_RENDERABOVEMAIN              2180
#define CM_SHELLOUTWAIT                 2185
#define CM_RENDERHIDE                   2190
#define CM_RENDERCLOSE                  2195
#define CM_CLEARMESSAGES                2200
#define CM_SAVE_SETTINGS                2205
#define CM_TIPOFTHEDAY                  2210
#define CM_SHOWNEXTTIP                  2215
#define CM_TINYCAPTION                  2220
#define CM_NONCLIENT                    2225
#define CM_HELPPOVCD                    2236
#define CM_HELPIRTCCD                   2237
#define CM_COMPLETION_EXIT              2240
#define CM_COMPLETION_MESSAGE           2250
#define CM_COMPLETION_NOTHING           2260
#define CM_COMPLETION_HAL               2265
#define CM_RENDERPRIORITY_LOW           2300
#define CM_RENDERPRIORITY_NORMAL        2305
#define CM_RENDERPRIORITY_HIGH          2310
#define CM_FILEOPEN                     2325
#define CM_FILENEW                      2330
#define CM_FILESAVEAS                   2340
#define CM_FILESAVE                     2345
#define CM_USETEMPLATE                  2355
#define CM_POVLEGAL                     2360
#define CM_SYSTEMNOACTIVE               2370
#define CM_SINGLEINSTANCE               2375
#define CM_USETOOLBAR                   2385
#define CM_USETOOLTIPS                  2390
#define CM_PREVWINDOW                   2395
#define CM_NEXTWINDOW                   2400
#define CM_DROPEDITOR                   2410
#define CM_DROPRENDERER                 2415
#define CM_USEEDITOR                    2420
#define CM_RENDERAUTOCLOSE              2425
#define CM_RENDERSLEEP                  2430
#define CM_USEEXTENSIONS                2435
#define CM_SHOWMAINWINDOW               2440
#define CM_GOPOVRAYORG                  2450
#define CM_GOIRTC                       2455
#define CM_FILECLOSE                    2460
#define CM_USERENDERANIM                2465
#define CM_IO_NO_RESTRICTIONS           2470
#define CM_IO_RESTRICT_WRITE            2471
#define CM_IO_RESTRICT_READWRITE        2472
#define CM_RW_SOURCE                    2475
#define CM_NO_SHELLOUTS                 2480
#define CM_SAVEIMAGE                    2485
#define CM_RENDERINSERT                 2490
#define CM_RERUN                        2600
#define CM_BACKGROUNDSTD                2700
#define CM_LOADTOOLMENU                 2800
#define CM_FIRSTTOOL                    2805
#define CM_LASTTOOL                     2855
#define CM_FIRSTEDITNOTIFY              2900
#define CM_LASTEDITNOTIFY               2925
#define CM_FIRSTMENUHELP                2930
#define CM_FILEMENUHELP                 2930
#define CM_EDITMENUHELP                 2931
#define CM_SEARCHMENUHELP               2932
#define CM_TEXTMENUHELP                 2933
#define CM_EDITORMENUHELP               2934
#define CM_RENDERMENUHELP               2935
#define CM_OPTIONSMENUHELP              2936
#define CM_TOOLSMENUHELP                2937
#define CM_GUIEXTMENUHELP               2938
#define CM_RENDERWINMENUHELP            2939
#define CM_MESSAGEWINMENUHELP           2940
#define CM_WINDOWMENUHELP               2941
#define CM_LASTMENUHELP                 2942
#define CM_HIDENEWUSERHELP              2945
#define CM_PRESERVERENDERBITMAP         2950
#define INSTANCE_COMMAND_MESSAGE        2955
#define CM_DUTYCYCLE_10                 2960
#define CM_DUTYCYCLE_20                 2961
#define CM_DUTYCYCLE_30                 2962
#define CM_DUTYCYCLE_40                 2963
#define CM_DUTYCYCLE_50                 2964
#define CM_DUTYCYCLE_60                 2965
#define CM_DUTYCYCLE_70                 2966
#define CM_DUTYCYCLE_80                 2967
#define CM_DUTYCYCLE_90                 2968
#define CM_DUTYCYCLE_100                2969
#define CM_CHECKNEWVERSION              2970
#define CM_CHECKNEWS                    2971
#define CM_SENDSYSTEMINFO               2972
#define CM_RENDERSOUNDS                 2980
#define IDC_COMMANDLINE                 3505
#define IDC_COPYRIGHT                   3510
#define IDC_GROUPBOX6                   3511
#define IDC_ACCESSORIES                 3512
#define IDC_GROUPBOX5                   3514
#define IDC_STATICTEXT1                 3515
#define IDC_STATICTEXT2                 3516
#define IDC_STATICTEXT3                 3517
#define IDC_STATICTEXT4                 3518
#define IDC_FILEQUEUE                   3520
#define IDC_CONTEXTHELP                 3521
#define IDC_LISTBOX                     3530
#define IDC_MESSAGES                    3535
#define IDC_READPOVLEGAL                3540
#define IDC_RENDER                      3545
#define IDC_RENDERa                     3546
#define IDC_RERUNLIST                   3550
#define IDC_SAVEPOVLEGAL                3555
#define IDC_SET                         3560
#define IDC_VERSION                     3565
#define IDC_ADDFILE                     3570
#define IDC_DELETEFILE                  3575
#define IDC_RERUN                       3580
#define IDC_STATISTICS                  3585
#define IDC_SHOWTIPS                    3590
#define IDC_PREVIOUSTIP                 3600
#define IDC_NEXTTIP                     3605
#define IDC_TIPFRAME                    3610
#define IDC_SHOWNEXTTIP                 3615
#define IDC_BROWSEINIFILE               3625
#define IDC_BROWSESOURCEFILE            3635
#define IDC_GROUPBOX1                   3645
#define IDC_GROUPBOX2                   3650
#define IDC_GROUPBOX3                   3655
#define IDC_GROUPBOX4                   3660
#define IDC_COMMANDHELP                 3670
#define IDC_INIFILESECTION              3675
#define IDC_RELOADQUEUE                 3690
#define IDC_QUEUEENTRIES                3695
#define IDC_AUTORENDER                  3700
#define IDC_PRESETSOURCENAME            3705
#define IDC_PRESETSOURCEPATH            3710
#define IDC_INIFILENAME                 3715
#define IDC_INIFILEPATH                 3720
#define IDC_RESETINI                    3725
#define IDC_EDITINI                     3730
#define IDC_INIDEFAULT                  3735
#define IDC_SOURCEDEFAULT               3740
#define IDC_TOOLBAR                     3745
#define IDC_EDITRENDER                  3750
#define IDC_RTR                         3755
#define IDC_ADVICETEXT                  3760
#define IDC_DONTTELLMEAGAIN             3765
#define IDC_ENABLE_RENDERCOMPLETESOUND  3770
#define IDC_BROWSE_RENDERCOMPLETESOUND  3775
#define IDC_SOUND_RENDERCOMPLETE        3780
#define IDC_ENABLE_PARSEERRORSOUND      3785
#define IDC_BROWSE_PARSEERRORSOUND      3790
#define IDC_SOUND_PARSEERROR            3795
#define IDC_ENABLE_RENDERERRORSOUND     3800
#define IDC_BROWSE_RENDERERRORSOUND     3805
#define IDC_SOUND_RENDERERROR           3810
#define IDD_ABOUT                       4000
#define IDD_COMMANDLINE                 4005
#define IDD_SHORTCOMMANDLINE            4007
#define IDD_FILEQUEUE                   4010
#define IDD_TIP                         4015
#define IDD_RERUN                       4020
#define IDD_VIEW                        4025
#define IDD_COMMFILE                    4030
#define IDD_FEATUREADVICE               4035
#define IDD_SOUNDS                      4040
#define IDI_PVENGINE_XP                 5000
#define IDI_RENDERWINDOW_XP             5005
#define IDI_PVENGINE                    5010
#define IDI_RENDERWINDOW                5015
#define PVENGINE_MENU                   6000
#define POPUP_MENUS                     6005
#define PVENGINE_MENU32                 6010
#define POPUP_MENUS32                   6015
#define BMP_BACKGROUND00                7000
#define BMP_BACKGROUND01                7001
#define BMP_BACKGROUND02                7002
#define BMP_BACKGROUND03                7003
#define BMP_BACKGROUND04                7004
#define BMP_ICON                        7110
#define BMP_REBAR                       7115
#define BMP_SPLASH_8BPP                 7117
#define BMP_SPLASH_8BPP_PAL             7120
#define BMP_TINYBAR                     7121
#define BMP_RENDERANIM                  7122
#define BMP_RENDERANIM_4BPP             7123
#define BMP_STRETCHDIBITS               7124
#define BMP_LOGO_1                      7219
#define BMP_WIDEICON                    7220
#define BMP_TOOLFILENEW                 7300
#define BMP_TOOLFILEOPEN                7301
#define BMP_TOOLFILESAVE                7302
#define BMP_TOOLFILEQUEUE               7303
#define BMP_TOOLRERUN                   7304
#define BMP_TOOLRENDERSHOW              7305
#define BMP_TOOLRENDERCLOSE             7306
#define BMP_TOOLCMDLINE                 7307
#define BMP_TOOLSOURCEFILE              7308
#define BMP_TOOLFILERENDER              7309
#define BMP_TOOLSTOPRENDER              7310
#define BMP_TOOLSLEEP                   7311
#define BMP_TOOLHELPCONT                7312
#define BMP_TOOLHELPPOVRAY              7313
#define BMP_TOOLHELPIRTCCD              7314
#define BMP_TOOLGOPOVRAY                7315
#define BMP_TOOLGOIRTC                  7316
#define BMP_TOOLSYSTRAY                 7317
#define BMP_TOOLHELPPOVCD               7318
#define BMP_TOOLFILECLOSE               7319
#define BMP_TOOLFILENEW_4BPP            7350
#define BMP_TOOLFILEOPEN_4BPP           7351
#define BMP_TOOLFILESAVE_4BPP           7352
#define BMP_TOOLFILEQUEUE_4BPP          7353
#define BMP_TOOLRERUN_4BPP              7354
#define BMP_TOOLRENDERSHOW_4BPP         7355
#define BMP_TOOLRENDERCLOSE_4BPP        7356
#define BMP_TOOLCMDLINE_4BPP            7357
#define BMP_TOOLSOURCEFILE_4BPP         7358
#define BMP_TOOLFILERENDER_4BPP         7359
#define BMP_TOOLSTOPRENDER_4BPP         7360
#define BMP_TOOLSLEEP_4BPP              7361
#define BMP_TOOLHELPCONT_4BPP           7362
#define BMP_TOOLHELPPOVRAY_4BPP         7363
#define BMP_TOOLHELPIRTCCD_4BPP         7364
#define BMP_TOOLGOPOVRAY_4BPP           7365
#define BMP_TOOLGOIRTC_4BPP             7366
#define BMP_TOOLSYSTRAY_4BPP            7367
#define BMP_TOOLHELPPOVCD_4BPP          7368
#define BMP_TOOLFILECLOSE_4BPP          7369
#define BMP_ABOUT                       7370
#define ID_REBAR                        8000
#define ID_STATUS                       8100
#define CM_FIRSTGUIEXT                  16384
#define CM_LASTGUIEXT                   20479
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        116
#define _APS_NEXT_COMMAND_VALUE         30024
#define _APS_NEXT_CONTROL_VALUE         1006
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
